[versions]
agoraRtm = "2.2.2"
agp = "8.3.0"
assertjCore = "3.13.2"
crashreportVersion = "4.1.9.3"
dsbridgeAndroid = "3.0.6"
gson = "2.11.0"
json = "20250517"
kotlin = "1.9.0"
coreKtx = "1.9.0"
junit = "4.13.2"
kotlinxCoroutinesTest = "1.7.3"
truth = "1.1.5"
androidxJunit = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
cardview = "1.0.0"
recyclerview = "1.2.1"
kotlinxCoroutinesCore = "1.7.1"
kotlinxCoroutinesAndroid = "1.7.1"
material = "1.8.0"
mockitoAndroid = "2.28.2"
mockitoKotlin = "4.1.0"
okhttpVersion = "4.7.2"
activity = "1.8.0"
constraintlayout = "2.0.4"
quickjsAndroid = "0.1.3"
agoraBoardForge = "1.1.2-beta01"
agoraForgeUi = "0.1.0"
materialVersion = "1.13.0"

[libraries]
agora-rtm = { module = "io.agora:agora-rtm", version.ref = "agoraRtm" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertjCore" }
bugly-crashreport = { module = "com.tencent.bugly:crashreport", version.ref = "crashreportVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Libraries for Agora Board
dsbridge-android = { module = "com.github.netless-io:DSBridge-Android", version.ref = "dsbridgeAndroid" }
quickjs-android = { module = "com.github.netless-io:quickjs-android", version.ref = "quickjsAndroid" }
agora-board-forge-yjs = { module = "io.github.duty-os.forge:forge-yjs", version.ref = "agoraBoardForge" }
agora-board-forge-room = { module = "io.github.duty-os.forge:forge-room", version.ref = "agoraBoardForge" }
agora-board-forge-rtmprovider = { module = "io.github.duty-os.forge:forge-rtmprovider", version.ref = "agoraBoardForge" }

# UI library for Agora Board Forge
agora-board-forge-ui = { module = "io.github.duty-os.forge:forge-ui", version.ref = "agoraForgeUi" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }

